people:
  - {name: Chris, email: chrisemail@email.com}
  - {name: Bob, email: bobemail@email.com}
  - {name: Dan, email: danemail@email.com}
  - {name: Jo, email: joemail@email.com}

pricelimit: '100'

template: 
  Ho ho hello {name}
 

  Your secret santa for this year is {match}.
  
  Price limit is about ${pricelimit}
  
  
  Warmest regards,

  Santa

template_html:
  <html><p>Ho ho hello {name}</p>
  <p>Your secret santa for this year is {match}.</p>
  <p>Price limit is about ${pricelimit}</p>
  <p>Warmest regards,</p>
  <p>Santa</p></html>

emailconfig:
  # smtpserver: smtp.gmail.com
  # smtpport: '465'
  # smtppwd: yourgmailpassword
  protocol: ses
  subject: Secret Santa!!
  fromemail: fromemailaddress
  sesawsprofile: awsprofilename
  sesawsregion: awsregion
